apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-service-deployment
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      component: auth-service
  template:
    metadata:
      labels:
        component: auth-service
    spec:
      containers:
        - name: auth-service
          image: "{{ .Values.global.registry }}/{{ .Values.images.auth.repository }}:{{ .Values.images.auth.tag }}"
          ports:
            - containerPort: 3001
          envFrom:
            - configMapRef:
                name: configmap
          env:
            - name: PORT
              valueFrom:
                configMapKeyRef:
                  name: configmap
                  key: AUTH_PORT
            - name: MONGO_URI
              valueFrom:
                configMapKeyRef:
                  name: configmap
                  key: MONGO_URI
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: streamingapp-secrets
                  key: JWT_SECRET
            - name: CLIENT_URLS
              valueFrom:
                configMapKeyRef:
                  name: configmap
                  key: CLIENT_URLS
            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: streamingapp-secrets
                  key: AWS_ACCESS_KEY_ID
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: streamingapp-secrets
                  key: AWS_SECRET_ACCESS_KEY
            - name: AWS_REGION
              valueFrom:
                configMapKeyRef:
                  name: configmap
                  key: AWS_REGION
            - name: AWS_S3_BUCKET
              valueFrom:
                configMapKeyRef:
                  name: configmap
                  key: AWS_S3_BUCKET
          livenessProbe:
            httpGet:
              path: /health
              port: 3001
            initialDelaySeconds: 5
            periodSeconds: 10
            timeoutSeconds: 5
            successThreshold: 1
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /health
              port: 3001
            initialDelaySeconds: 5
            periodSeconds: 10
            timeoutSeconds: 5
            successThreshold: 1
            failureThreshold: 3
          resources:
            requests:
              cpu: {{ .Values.resources.requests.cpu | quote }}
              memory: {{ .Values.resources.requests.memory | quote }}
            limits:
              cpu: {{ .Values.resources.limits.cpu | quote }}
              memory: {{ .Values.resources.limits.memory | quote }}
---
apiVersion: v1
kind: Service
metadata:
  name: auth-service-service
spec:
  type: ClusterIP
  selector:
    component: auth-service
  ports:
    - port: 3001
      targetPort: 3001
