apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      component: frontend
  template:
    metadata:
      labels:
        component: frontend
    spec:
      containers:
        - name: frontend
          image: "{{ .Values.global.registry }}/{{ .Values.images.frontend.repository }}:{{ .Values.images.frontend.tag }}"
          ports:
            - containerPort: 80
          envFrom:
            - configMapRef:
                name: configmap
          resources:
            requests:
              cpu: {{ .Values.resources.requests.cpu | quote }}
              memory: {{ .Values.resources.requests.memory | quote }}
            limits:
              cpu: {{ .Values.resources.limits.cpu | quote }}
              memory: {{ .Values.resources.limits.memory | quote }}
---
apiVersion: v1
kind: Service
metadata:
  name: frontend
spec:
  type: NodePort
  selector:
    component: frontend
  ports:
    - port: 80
      targetPort: 80
